# Generated by Django 5.0.3 on 2024-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0002_user_gender_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_names',
            field=models.CharField(default='first_name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_names',
            field=models.CharField(default='last_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=255),
        ),
    ]
