# Generated by Django 5.0.3 on 2024-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0003_user_first_names_user_last_names_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_names',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last_name', max_length=255),
        ),
    ]
