# Generated by Django 5.0.3 on 2024-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0004_remove_user_first_names_remove_user_last_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar/'),
        ),
    ]
